const trainData = [
  {
    id: 1,
    source: "Andheri",
    destination: "Churchgate",
    type: "Fast",
    line: "Western",
    timing: "10:30 AM",
    currentLocation: "Bandra",
    coveredStations: [
      "Andheri",
      "Bandra",
      "Dadar",
      "Mumbai Central",
      "Churchgate",
    ],
  },
  {
    id: 2,
    source: "Borivali",
    destination: "Churchgate",
    type: "Slow",
    line: "Western",
    timing: "11:00 AM",
    currentLocation: "Malad",
    coveredStations: [
      "Borivali",
      "Kandivali",
      "Malad",
      "Andheri",
      "Dadar",
      "Churchgate",
    ],
  },
  {
    id: 3,
    source: "Kurla",
    destination: "CST",
    type: "Fast",
    line: "Central",
    timing: "10:45 AM",
    currentLocation: "Dadar",
    coveredStations: ["Kurla", "Dadar", "Byculla", "CST"],
  },
  {
    id: 4,
    source: "Thane",
    destination: "CST",
    type: "Semi Fast",
    line: "Central",
    timing: "11:15 AM",
    currentLocation: "Ghatkopar",
    coveredStations: [
      "Thane",
      "Mulund",
      "Bhandup",
      "Ghatkopar",
      "Dadar",
      "CST",
    ],
  },
  {
    id: 5,
    source: "Vashi",
    destination: "Panvel",
    type: "Slow",
    line: "Harbour",
    timing: "10:50 AM",
    currentLocation: "Nerul",
    coveredStations: ["Vashi", "Sanpada", "Belapur", "Kharghar", "Panvel"],
  },
  {
    id: 6,
    source: "Bandra",
    destination: "CST",
    type: "Fast",
    line: "Harbour",
    timing: "11:05 AM",
    currentLocation: "Wadala",
    coveredStations: ["Bandra", "Mahim", "Wadala", "Kurla", "CST"],
  },
  {
    id: 7,
    source: "Borivali",
    destination: "Bandra",
    type: "Fast",
    line: "Western",
    timing: "12:00 PM",
    currentLocation: "Andheri",
    coveredStations: ["Borivali", "Kandivali", "Malad", "Andheri", "Bandra"],
  },
  {
    id: 8,
    source: "Thane",
    destination: "Vashi",
    type: "Slow",
    line: "Trans-Harbour",
    timing: "01:00 PM",
    currentLocation: "Airoli",
    coveredStations: ["Thane", "Airoli", "Rabale", "Ghansoli", "Vashi"],
  },
  {
    id: 9,
    source: "CST",
    destination: "Panvel",
    type: "Semi Fast",
    line: "Harbour",
    timing: "02:00 PM",
    currentLocation: "Belapur",
    coveredStations: ["CST", "Wadala", "Vashi", "Nerul", "Belapur", "Panvel"],
  },
  {
    id: 10,
    source: "Dadar",
    destination: "Borivali",
    type: "Slow",
    line: "Western",
    timing: "03:15 PM",
    currentLocation: "Andheri",
    coveredStations: ["Dadar", "Bandra", "Andheri", "Malad", "Borivali"],
  },
  {
    id: 11,
    source: "Andheri",
    destination: "Borivali",
    type: "Fast",
    line: "Western",
    timing: "03:30 PM",
    currentLocation: "Dadar",
    coveredStations: ["Andheri", "Bandra", "Kandivali", "Borivali"],
  },
  {
    id: 12,
    source: "Kurla",
    destination: "Vashi",
    type: "Semi Fast",
    line: "Central",
    timing: "04:00 PM",
    currentLocation: "Ghatkopar",
    coveredStations: ["Kurla", "Dadar", "Vashi"],
  },
  {
    id: 13,
    source: "Malad",
    destination: "Churchgate",
    type: "Slow",
    line: "Western",
    timing: "04:30 PM",
    currentLocation: "Bandra",
    coveredStations: ["Malad", "Kandivali", "Andheri", "Bandra", "Churchgate"],
  },
  {
    id: 14,
    source: "Ghatkopar",
    destination: "CST",
    type: "Fast",
    line: "Central",
    timing: "05:00 PM",
    currentLocation: "Thane",
    coveredStations: ["Ghatkopar", "Mulund", "Bhandup", "Dadar", "CST"],
  },
  {
    id: 15,
    source: "Vashi",
    destination: "Panvel",
    type: "Slow",
    line: "Harbour",
    timing: "05:10 PM",
    currentLocation: "Belapur",
    coveredStations: ["Vashi", "Sanpada", "Nerul", "Belapur", "Panvel"],
  },
  {
    id: 16,
    source: "Bandra",
    destination: "Kurla",
    type: "Fast",
    line: "Harbour",
    timing: "05:30 PM",
    currentLocation: "Wadala",
    coveredStations: ["Bandra", "Mahim", "Wadala", "Kurla"],
  },
  {
    id: 17,
    source: "Borivali",
    destination: "Churchgate",
    type: "Semi Fast",
    line: "Western",
    timing: "06:00 PM",
    currentLocation: "Malad",
    coveredStations: [
      "Borivali",
      "Kandivali",
      "Malad",
      "Andheri",
      "Churchgate",
    ],
  },
  {
    id: 18,
    source: "Dadar",
    destination: "Thane",
    type: "Fast",
    line: "Central",
    timing: "06:15 PM",
    currentLocation: "Kurla",
    coveredStations: ["Dadar", "Kurla", "Thane"],
  },
  {
    id: 19,
    source: "Andheri",
    destination: "Vashi",
    type: "Slow",
    line: "Western",
    timing: "06:45 PM",
    currentLocation: "Bandra",
    coveredStations: ["Andheri", "Kandivali", "Malad", "Bandra", "Vashi"],
  },
  {
    id: 20,
    source: "Churchgate",
    destination: "CST",
    type: "Fast",
    line: "Harbour",
    timing: "07:00 PM",
    currentLocation: "Dadar",
    coveredStations: ["Churchgate", "Dadar", "Wadala", "Kurla", "CST"],
  },
  {
    id: 21,
    source: "Bandra",
    destination: "Vashi",
    type: "Fast",
    line: "Harbour",
    timing: "07:30 PM",
    currentLocation: "Wadala",
    coveredStations: ["Bandra", "Mahim", "Vashi"],
  },
  {
    id: 22,
    source: "Borivali",
    destination: "Dadar",
    type: "Fast",
    line: "Western",
    timing: "08:00 PM",
    currentLocation: "Malad",
    coveredStations: ["Borivali", "Kandivali", "Malad", "Bandra", "Dadar"],
  },
  {
    id: 23,
    source: "CST",
    destination: "Vashi",
    type: "Slow",
    line: "Harbour",
    timing: "08:30 PM",
    currentLocation: "Belapur",
    coveredStations: ["CST", "Wadala", "Kurla", "Vashi"],
  },
  {
    id: 24,
    source: "Ghatkopar",
    destination: "Churchgate",
    type: "Fast",
    line: "Central",
    timing: "09:00 PM",
    currentLocation: "Mulund",
    coveredStations: ["Ghatkopar", "Dadar", "Churchgate"],
  },
  {
    id: 25,
    source: "Thane",
    destination: "Andheri",
    type: "Slow",
    line: "Central",
    timing: "09:30 PM",
    currentLocation: "Mulund",
    coveredStations: ["Thane", "Bhandup", "Ghatkopar", "Andheri"],
  },
  {
    id: 26,
    source: "Vashi",
    destination: "CST",
    type: "Fast",
    line: "Harbour",
    timing: "10:00 PM",
    currentLocation: "Belapur",
    coveredStations: ["Vashi", "Sanpada", "Nerul", "CST"],
  },
  {
    id: 27,
    source: "Bandra",
    destination: "Vashi",
    type: "Fast",
    line: "Western",
    timing: "10:30 PM",
    currentLocation: "Andheri",
    coveredStations: ["Bandra", "Andheri", "Vashi"],
  },
  {
    id: 28,
    source: "Malad",
    destination: "Dadar",
    type: "Semi Fast",
    line: "Western",
    timing: "11:00 PM",
    currentLocation: "Kandivali",
    coveredStations: ["Malad", "Kandivali", "Andheri", "Dadar"],
  },
  {
    id: 29,
    source: "Kurla",
    destination: "Vashi",
    type: "Slow",
    line: "Central",
    timing: "11:30 PM",
    currentLocation: "Dadar",
    coveredStations: ["Kurla", "Vashi"],
  },
  {
    id: 30,
    source: "Andheri",
    destination: "Panvel",
    type: "Fast",
    line: "Harbour",
    timing: "12:00 AM",
    currentLocation: "Bandra",
    coveredStations: ["Andheri", "Dadar", "Vashi", "Panvel"],
  },
  {
    id: 31,
    source: "Thane",
    destination: "Churchgate",
    type: "Slow",
    line: "Central",
    timing: "12:30 AM",
    currentLocation: "Mulund",
    coveredStations: [
      "Thane",
      "Mulund",
      "Bhandup",
      "Kurla",
      "Dadar",
      "Churchgate",
    ],
  },
  {
    id: 32,
    source: "Dadar",
    destination: "Panvel",
    type: "Semi Fast",
    line: "Western",
    timing: "01:00 AM",
    currentLocation: "Malad",
    coveredStations: ["Dadar", "Bandra", "Andheri", "Vashi", "Panvel"],
  },
  {
    id: 33,
    source: "Bandra",
    destination: "Kurla",
    type: "Fast",
    line: "Harbour",
    timing: "01:30 AM",
    currentLocation: "Wadala",
    coveredStations: ["Bandra", "Wadala", "Kurla"],
  },
  {
    id: 34,
    source: "Borivali",
    destination: "Thane",
    type: "Slow",
    line: "Western",
    timing: "02:00 AM",
    currentLocation: "Kandivali",
    coveredStations: ["Borivali", "Malad", "Goregaon", "Dadar", "Thane"],
  },
  {
    id: 35,
    source: "Churchgate",
    destination: "Bandra",
    type: "Fast",
    line: "Western",
    timing: "02:30 AM",
    currentLocation: "Andheri",
    coveredStations: ["Churchgate", "Dadar", "Bandra"],
  },
  {
    id: 36,
    source: "Vashi",
    destination: "Kurla",
    type: "Slow",
    line: "Harbour",
    timing: "03:00 AM",
    currentLocation: "Nerul",
    coveredStations: ["Vashi", "Sanpada", "Kurla"],
  },
  {
    id: 37,
    source: "CST",
    destination: "Thane",
    type: "Fast",
    line: "Central",
    timing: "03:30 AM",
    currentLocation: "Byculla",
    coveredStations: ["CST", "Dadar", "Thane"],
  },
  {
    id: 38,
    source: "Malad",
    destination: "Vashi",
    type: "Semi Fast",
    line: "Western",
    timing: "04:00 AM",
    currentLocation: "Bandra",
    coveredStations: ["Malad", "Kandivali", "Bandra", "Vashi"],
  },
  {
    id: 39,
    source: "Dadar",
    destination: "Kurla",
    type: "Slow",
    line: "Central",
    timing: "04:30 AM",
    currentLocation: "Ghatkopar",
    coveredStations: ["Dadar", "Kurla"],
  },
  {
    id: 40,
    source: "Bandra",
    destination: "CST",
    type: "Fast",
    line: "Harbour",
    timing: "05:00 AM",
    currentLocation: "Wadala",
    coveredStations: ["Bandra", "Wadala", "CST"],
  },
  {
    id: 41,
    source: "Andheri",
    destination: "Thane",
    type: "Fast",
    line: "Western",
    timing: "05:30 AM",
    currentLocation: "Malad",
    coveredStations: ["Andheri", "Malad", "Dadar", "Thane"],
  },
  {
    id: 42,
    source: "Bandra",
    destination: "Malad",
    type: "Slow",
    line: "Western",
    timing: "06:00 AM",
    currentLocation: "Andheri",
    coveredStations: ["Bandra", "Andheri", "Malad"],
  },
  {
    id: 43,
    source: "Dadar",
    destination: "CST",
    type: "Fast",
    line: "Central",
    timing: "06:30 AM",
    currentLocation: "Kurla",
    coveredStations: ["Dadar", "Kurla", "CST"],
  },
  {
    id: 44,
    source: "Kurla",
    destination: "Bandra",
    type: "Fast",
    line: "Central",
    timing: "07:00 AM",
    currentLocation: "Mulund",
    coveredStations: ["Kurla", "Dadar", "Bandra"],
  },
  {
    id: 45,
    source: "Panvel",
    destination: "Thane",
    type: "Semi Fast",
    line: "Harbour",
    timing: "07:30 AM",
    currentLocation: "Nerul",
    coveredStations: ["Panvel", "Vashi", "Nerul", "Thane"],
  },
  {
    id: 46,
    source: "Vashi",
    destination: "CST",
    type: "Fast",
    line: "Harbour",
    timing: "08:00 AM",
    currentLocation: "Nerul",
    coveredStations: ["Vashi", "Sanpada", "CST"],
  },
  {
    id: 47,
    source: "Kurla",
    destination: "Thane",
    type: "Slow",
    line: "Central",
    timing: "08:30 AM",
    currentLocation: "Ghatkopar",
    coveredStations: ["Kurla", "Dadar", "Thane"],
  },
  {
    id: 48,
    source: "Andheri",
    destination: "Vashi",
    type: "Fast",
    line: "Western",
    timing: "09:00 AM",
    currentLocation: "Malad",
    coveredStations: ["Andheri", "Malad", "Bandra", "Vashi"],
  },
  {
    id: 49,
    source: "CST",
    destination: "Vashi",
    type: "Slow",
    line: "Harbour",
    timing: "09:30 AM",
    currentLocation: "Wadala",
    coveredStations: ["CST", "Wadala", "Vashi"],
  },
  {
    id: 50,
    source: "Borivali",
    destination: "Dadar",
    type: "Fast",
    line: "Western",
    timing: "10:00 AM",
    currentLocation: "Andheri",
    coveredStations: ["Borivali", "Kandivali", "Malad", "Andheri", "Dadar"],
  },
];

export const getTrains = () => trainData;

export const getSourceStations = (lineFilter = "All") => {
  const stations = trainData
    .filter((train) => lineFilter === "All" || train.line === lineFilter)
    .map((train) => train.source);
  return [...new Set(stations)];
};

export const getDestinationStations = (source) => {
  const destinations = trainData
    .filter((train) => train.source === source)
    .map((train) =>
      train.coveredStations.filter((station) => station !== source)
    )
    .flat();
  return [...new Set(destinations)];
};
